package router

func init() {
	webSearchKeywords = append(webSearchKeywords,
		// News & Journalism
		"notícias", "jornal", "manchete", "reportagem", "cobertura", "jornalismo", "imprensa", "mídia",
		"veículo", "publicação", "edição", "jornalista", "repórter", "matéria", "artigo", "texto jornalístico",
		"breaking news", "notícia de última hora", "notícia urgente", "notícia importante",
		"últimas notícias", "notícias recentes", "notícias de hoje", "noticiário", "boletim", "informativo",
		"plantão", "extra", "furo de reportagem", "exclusivo", "em primeira mão", "furo jornalístico",
		"coluna", "editorial", "opinião pública", "repercussão", "escândalo", "polêmica", "denúncia",
		"investigação jornalística", "coletiva de imprensa", "entrevista coletiva", "comunicado oficial",
		"nota oficial", "pronunciamento", "discurso", "declaração", "anúncio", "revelação", "vazamento",
		"fontes", "bastidores", "fofoca", "celebridades", "famosos", "mundo dos famosos", "entretenimento",
		"variedades", "cultura pop", "viral", "trending", "tendências", "assuntos do momento", "tópicos quentes",
		"hashtag", "twitter", "facebook", "instagram", "tiktok", "youtube", "rede social", "mídias sociais",

		// Time-sensitive & Real-time
		"hoje", "agora", "atual", "recente", "último", "mais recente", "atualmente", "neste momento",
		"agora mesmo", "neste instante", "neste exato momento", "atualidade", "atualização",
		"em tempo real", "ao vivo", "live", "transmissão ao vivo", "minuto a minuto", "tempo real",
		"nesta semana", "neste mês", "neste ano", "ontem", "anteontem", "amanhã", "depois de amanhã",
		"fim de semana", "feriado", "próximo", "futuro", "previsão", "tendência", "expectativa",
		"agendado", "programado", "marcado", "adiado", "cancelado", "confirmado", "rumor", "especulação",
		"novidade", "lançamento", "estreia", "inauguração", "abertura", "encerramento", "fechamento",

		// Prices, Finance & Economy
		"cotação", "preço", "valor", "dólar", "euro", "bitcoin", "ações", "bolsa", "ibovespa",
		"mercado financeiro", "câmbio", "taxa de câmbio", "moeda", "criptomoeda", "investimento",
		"papéis", "renda variável", "renda fixa", "selic", "cdi", "ipca", "inflação",
		"taxa selic", "taxa básica", "juros", "rentabilidade", "lucro", "prejuízo", "patrimônio", "fortuna",
		"preço atual", "dólar hoje", "euro hoje", "bitcoin hoje", "ethereum", "litecoin", "blockchain",
		"nft", "defi", "fintech", "banco", "corretora", "carteira", "fundo de investimento", "tesouro direto",
		"poupança", "lci", "lca", "cdb", "debentures", "dividendos", "proventos", "fii", "fundos imobiliários",
		"imposto de renda", "receita federal", "leão", "malha fina", "restituição", "darf", "boleto",
		"fatura", "cartão de crédito", "crédito", "débito", "financiamento", "empréstimo", "hipoteca",
		"consórcio", "seguro", "previdência", "aposentadoria", "inss", "fgts", "pis", "pasep",
		"salário", "remuneração", "bônus", "plr", "dissídio", "sindicato", "greve", "paralisação",
		"economia", "macroeconomia", "microeconomia", "pib", "recessão", "crise", "crescimento",
		"desenvolvimento", "exportação", "importação", "balança comercial", "superávit", "déficit",
		"dívida pública", "orçamento", "teto de gastos", "reforma tributária", "reforma administrativa",

		// Weather & Environment
		"tempo", "clima", "previsão", "chuva", "temperatura", "previsão do tempo", "clima hoje",
		"vai chover", "faz calor", "faz frio", "umidade", "vento", "precipitação", "neve", "granizo",
		"temporal", "tempestade", "chuva forte", "seca", "enchente", "alagamento", "geada", "neblina", "névoa",
		"tempo agora", "meteorologia", "climatempo", "inmet", "cptec", "satélite", "radar", "frente fria",
		"frente quente", "zona de convergência", "el niño", "la niña", "aquecimento global", "mudança climática",
		"efeito estufa", "camada de ozônio", "poluição", "qualidade do ar", "índice uv", "radiação solar",
		"nascer do sol", "pôr do sol", "fase da lua", "maré", "tábua de marés", "ressaca", "ciclone",
		"furacão", "tufão", "tornado", "terremoto", "tsunami", "vulcão", "erupção", "desmatamento",
		"queimada", "incêndio florestal", "amazônia", "pantanal", "cerrado", "mata atlântica", "caatinga",
		"pampa", "bioma", "biodiversidade", "sustentabilidade", "ecologia", "meio ambiente", "preservação",

		// Sports
		"jogo", "partida", "resultado", "placar", "campeonato", "liga", "time", "equipe", "atleta", "jogador",
		"esporte", "futebol", "basquete", "vôlei", "tênis", "natação", "atletismo", "olimpíadas", "mundial",
		"copa", "brasileirão", "libertadores", "copa do brasil", "estadual", "série a", "série b",
		"artilheiro", "gols", "pontos", "vitória", "derrota", "empate", "jogo de hoje", "tabela",
		"classificação", "rodada", "fase de grupos", "mata-mata", "quartas de final", "semifinal", "final",
		"decisão", "título", "taça", "troféu", "medalha", "ouro", "prata", "bronze", "pódio",
		"recorde", "superação", "doping", "lesão", "contratação", "transferência", "mercado da bola",
		"técnico", "treinador", "árbitro", "juiz", "bandeirinha", "var", "pênalti", "falta",
		"cartão amarelo", "cartão vermelho", "expulsão", "substituição", "acréscimos", "prorrogação",
		"pênaltis", "disputa de pênaltis", "torcida", "estádio", "arena", "ingresso", "sócio torcedor",
		"fórmula 1", "f1", "corrida", "gp", "grande prêmio", "pole position", "grid", "largada",
		"chegada", "podium", "piloto", "equipe", "construtores", "box", "pit stop", "ultrapassagem",
		"mma", "ufc", "luta", "combate", "octógono", "cinturão", "nocaute", "finalização", "pesagem",
		"boxe", "judô", "jiu-jitsu", "karatê", "taekwondo", "surfe", "skate", "ginástica",

		// Events, Politics & Society
		"aconteceu", "acontecendo", "ocorreu", "evento", "incidente", "acidente", "tragédia", "catástrofe",
		"desastre", "política", "eleição", "votação", "plebiscito", "referendo", "governo", "presidente",
		"ministro", "deputado", "senador", "prefeito", "governador", "eleito", "candidato", "campanha",
		"votar", "urna", "apuração", "democracia", "ditadura", "golpe", "impeachment", "cassação",
		"corrupção", "lava jato", "pf", "polícia federal", "stf", "supremo tribunal federal", "congresso",
		"câmara", "senado", "planalto", "alvorada", "itamaraty", "esplanada", "manifestação", "protesto",
		"passeata", "greve", "paralisação", "reivindicação", "sindicato", "movimento social", "ong",
		"direitos humanos", "cidadania", "constituição", "lei", "projeto de lei", "medida provisória",
		"decreto", "portaria", "resolução", "julgamento", "sentença", "condenação", "absolvição",
		"prisão", "liberdade", "habeas corpus", "fiança", "delegacia", "boletim de ocorrência", "crime",
		"assalto", "roubo", "furto", "homicídio", "assassinato", "feminicídio", "violência", "segurança",
		"saúde", "educação", "transporte", "habitação", "saneamento", "infraestrutura", "obras",

		// Technology & Science
		"tecnologia", "inovação", "ciência", "descoberta", "pesquisa", "estudo", "artigo científico",
		"nasa", "esa", "spacex", "foguete", "satélite", "missão espacial", "marte", "lua", "universo",
		"galáxia", "estrela", "planeta", "asteroide", "cometa", "buraco negro", "big bang", "física",
		"química", "biologia", "medicina", "vacina", "vírus", "bactéria", "doença", "cura", "tratamento",
		"medicamento", "remédio", "farmácia", "hospital", "médico", "enfermeiro", "paciente", "cirurgia",
		"inteligência artificial", "ia", "ai", "machine learning", "aprendizado de máquina", "deep learning",
		"rede neural", "algoritmo", "robô", "robótica", "automação", "internet", "web", "online",
		"offline", "conexão", "wifi", "5g", "4g", "fibra óptica", "banda larga", "smartphone",
		"celular", "iphone", "android", "app", "aplicativo", "software", "hardware", "computador",
		"notebook", "laptop", "tablet", "gadget", "dispositivo", "eletrônico", "game", "jogo",
		"console", "playstation", "xbox", "nintendo", "pc gamer", "steam", "twitch", "streamer",

		// Geography & Places (Expanded)
		"brasil", "estados unidos", "china", "rússia", "índia", "japão", "alemanha", "reino unido", "frança", "itália",
		"canadá", "austrália", "espanha", "méxico", "indonésia", "países baixos", "arábia saudita", "turquia", "suíça",
		"argentina", "suécia", "polônia", "bélgica", "tailândia", "irã", "áustria", "noruega", "emirados árabes unidos",
		"nigéria", "israel", "áfrica do sul", "hong kong", "irlanda", "dinamarca", "singapura", "malásia", "colômbia",
		"filipinas", "paquistão", "chile", "finlândia", "bangladesh", "egito", "vietnã", "portugal", "república checa",
		"romênia", "peru", "nova zelândia", "grécia", "iraque", "argélia", "cazaquistão", "hungria", "catar",
		"são paulo", "rio de janeiro", "nova york", "londres", "paris", "tóquio", "pequim", "moscou", "berlim", "roma",
		"madrid", "brasília", "buenos aires", "lisboa", "amsterdã", "bruxelas", "viena", "seul", "bangkok", "jacarta",
		"cairo", "istambul", "teerã", "bagdá", "riade", "dubai", "abu dhabi", "doha", "kuwait", "tel aviv",
		"jerusalém", "beirute", "damasco", "amã", "mascate", "sana", "cabul", "islamabad", "nova délhi", "mumbai",
		"xangai", "hong kong", "taipé", "manila", "hanoi", "ho chi minh", "kuala lumpur", "singapura", "sydney", "melbourne",
		"auckland", "wellington", "camberra", "toronto", "vancouver", "montreal", "ottawa", "chicago", "los angeles", "são francisco",
		"miami", "orlando", "las vegas", "washington", "boston", "filadélfia", "houston", "dallas", "atlanta", "seattle",
		"américa do sul", "américa do norte", "américa central", "europa", "ásia", "áfrica", "oceania", "antártida",
		"atlântico", "pacífico", "índico", "ártico", "antártico", "mediterrâneo", "caribe", "golfo pérsico", "mar vermelho",

		// Famous People & Entities
		"neymar", "messi", "cristiano ronaldo", "pelé", "maradona", "mbappé", "haaland", "vinicius junior", "anitta",
		"ivete sangalo", "gusttavo lima", "marília mendonça", "lula", "bolsonaro", "biden", "trump", "putin", "zelensky",
		"xi jinping", "papa francisco", "elon musk", "jeff bezos", "bill gates", "mark zuckerberg", "steve jobs",
		"google", "apple", "microsoft", "amazon", "facebook", "meta", "tesla", "spacex", "netflix", "disney",
		"globo", "sbt", "record", "band", "cnn", "bbc", "new york times", "folha de s.paulo", "estadão",
		"flamengo", "corinthians", "palmeiras", "são paulo", "vasco", "santos", "grêmio", "internacional", "cruzeiro",
		"atlético mineiro", "botafogo", "fluminense", "bahia", "vitória", "sport", "náutico", "santa cruz", "fortaleza",
		"ceará", "real madrid", "barcelona", "manchester city", "manchester united", "liverpool", "chelsea", "arsenal",
		"juventus", "milan", "inter de milão", "bayern de munique", "borussia dortmund", "psg", "boca juniors", "river plate",

		// Food & Places (often require local search)
		"restaurante", "restaurantes", "bistrô", "bistro", "padaria", "lanchonete", "cafeteria", "café",
		"bar", "bares", "boteco", "botecos", "pub", "gastropub", "churrascaria", "rodízio", "pizzaria",
		"hamburgueria", "food truck", "foodtruck", "delivery de comida", "entrega de comida", "melhor pizza",
		"melhor hambúrguer", "comida japonesa", "sushi perto", "rodízio de carne", "rodízio de pizza",
	)
}
